export const events = [
    {
        id: 1,
        latitude: 39.5134274,
        longitude: -8.687879,
        title: "Festas em Honra de Nossa Senhora da Conceiçao",
        description: "desc1",
        image: "https://i.pinimg.com/originals/86/60/97/866097e05986c369e0db5f3658182f60.jpg",
        artista1: "Bob Marley",
        artista2: "Mike Davis",
        artista3: "Xutos e pontapes",
        dataInicio: '2020-10-11',
        dataFinal: '2020-12-11',
        codigo: "0001",
        art: ["isabel", "fernado", "mendes", "Antonio moço", "isabel", "fernado", "mendes", "Antonio moço"],
        allImages: [{
            photo: "https://source.unsplash.com/aZjw7xI3QAA/1144x763",
            caption: "Viñales, Pinar del Río, Cuba",
            subcaption: "Photo by Simon Matzinger on Unsplash",
            thumbnail: "https://source.unsplash.com/aZjw7xI3QAA/100x67",
        }, {
            photo: "https://source.unsplash.com/c77MgFOt7e0/1144x763",
            caption: "La Habana, Cuba",
            subcaption: "Photo by Gerardo Sanchez on Unsplash",
            thumbnail: "https://source.unsplash.com/c77MgFOt7e0/100x67",
        }, {
            photo: "https://source.unsplash.com/QdBHnkBdu4g/1144x763",
            caption: "Woman smoking a tobacco",
            subcaption: "Photo by Hannah Cauhepe on Unsplash",
            thumbnail: "https://source.unsplash.com/QdBHnkBdu4g/100x67",
        }]
    },
    {
        id: 2,
        latitude: 39.5309549,
        longitude: -8.6728055,
        title: "Festas em Honra de Nossa Senhora da Conceiçao em  pensamento ",
        description: "desc2",
        image: "https://www.cm-moita.pt/cmmoita/uploads/news/image/4616/cartaz_festa_da_moita_2018.jpg",
        artista1: "Jay z",
        artista2: "Zara G",
        artista3: "Leonor Matado",
        dataInicio: '2020-01-11',
        dataFinal: '2020-09-11',
        codigo: "0002",
        art: [],
        allImages: [{
            photo: "https://source.unsplash.com/aZjw7xI3QAA/1144x763",
            caption: "Viñales, Pinar del Río, Cuba",
            subcaption: "Photo by Simon Matzinger on Unsplash",
            thumbnail: "https://source.unsplash.com/aZjw7xI3QAA/100x67",
        }, {
            photo: "https://source.unsplash.com/c77MgFOt7e0/1144x763",
            caption: "La Habana, Cuba",
            subcaption: "Photo by Gerardo Sanchez on Unsplash",
            thumbnail: "https://source.unsplash.com/c77MgFOt7e0/100x67",
        }, {
            photo: "https://source.unsplash.com/QdBHnkBdu4g/1144x763",
            caption: "Woman smoking a tobacco",
            subcaption: "Photo by Hannah Cauhepe on Unsplash",
            thumbnail: "https://source.unsplash.com/QdBHnkBdu4g/100x67",
        }]
    },
    {
        id: 3,
        latitude: 39.5134274,
        longitude: -8.687879,
        title: "Festa 3",
        description: "desc1",
        image: "https://i.pinimg.com/originals/86/60/97/866097e05986c369e0db5f3658182f60.jpg",
        artista1: "Bob Marley",
        artista2: "Mike Davis",
        artista3: "Xutos e pontapes",
        dataInicio: '2020-03-11',
        dataFinal: '2020-05-11',
        codigo: "0003",
        art: [],
        allImages: [{
            photo: "https://source.unsplash.com/aZjw7xI3QAA/1144x763",
            caption: "Viñales, Pinar del Río, Cuba",
            subcaption: "Photo by Simon Matzinger on Unsplash",
            thumbnail: "https://source.unsplash.com/aZjw7xI3QAA/100x67",
        }, {
            photo: "https://source.unsplash.com/c77MgFOt7e0/1144x763",
            caption: "La Habana, Cuba",
            subcaption: "Photo by Gerardo Sanchez on Unsplash",
            thumbnail: "https://source.unsplash.com/c77MgFOt7e0/100x67",
        }, {
            photo: "https://source.unsplash.com/QdBHnkBdu4g/1144x763",
            caption: "Woman smoking a tobacco",
            subcaption: "Photo by Hannah Cauhepe on Unsplash",
            thumbnail: "https://source.unsplash.com/QdBHnkBdu4g/100x67",
        }]
    },
    {
        id: 4,
        latitude: 39.5134274,
        longitude: -8.687879,
        title: "Festa 4",
        description: "desc1",
        image: "https://i.pinimg.com/originals/86/60/97/866097e05986c369e0db5f3658182f60.jpg",
        artista1: "Jay z",
        artista2: "Mike Davis",
        artista3: "Xutos e pontapes",
        dataInicio: '2020-06-23',
        dataFinal: '2020-06-26',
        codigo: "0004",
        art: [],
        allImages: [{
            photo: "https://source.unsplash.com/aZjw7xI3QAA/1144x763",
            caption: "Viñales, Pinar del Río, Cuba",
            subcaption: "Photo by Simon Matzinger on Unsplash",
            thumbnail: "https://source.unsplash.com/aZjw7xI3QAA/100x67",
        }, {
            photo: "https://source.unsplash.com/c77MgFOt7e0/1144x763",
            caption: "La Habana, Cuba",
            subcaption: "Photo by Gerardo Sanchez on Unsplash",
            thumbnail: "https://source.unsplash.com/c77MgFOt7e0/100x67",
        }, {
            photo: "https://source.unsplash.com/QdBHnkBdu4g/1144x763",
            caption: "Woman smoking a tobacco",
            subcaption: "Photo by Hannah Cauhepe on Unsplash",
            thumbnail: "https://source.unsplash.com/QdBHnkBdu4g/100x67",
        }]
    },
    {
        id: 5,
        latitude: 39.5309549,
        longitude: -8.6728055,
        title: "Festa 5",
        description: "desc2",
        image: "https://www.cm-moita.pt/cmmoita/uploads/news/image/4616/cartaz_festa_da_moita_2018.jpg",
        artista1: "Jay z",
        artista2: "Ribeiro",
        artista3: "Leonor Matado",
        dataInicio: '2020-05-11',
        dataFinal: '2020-06-11',
        codigo: "0005",
        art: [],
        allImages: [{
            photo: "https://source.unsplash.com/aZjw7xI3QAA/1144x763",
            caption: "Viñales, Pinar del Río, Cuba",
            subcaption: "Photo by Simon Matzinger on Unsplash",
            thumbnail: "https://source.unsplash.com/aZjw7xI3QAA/100x67",
        }, {
            photo: "https://source.unsplash.com/c77MgFOt7e0/1144x763",
            caption: "La Habana, Cuba",
            subcaption: "Photo by Gerardo Sanchez on Unsplash",
            thumbnail: "https://source.unsplash.com/c77MgFOt7e0/100x67",
        }, {
            photo: "https://source.unsplash.com/QdBHnkBdu4g/1144x763",
            caption: "Woman smoking a tobacco",
            subcaption: "Photo by Hannah Cauhepe on Unsplash",
            thumbnail: "https://source.unsplash.com/QdBHnkBdu4g/100x67",
        }]
    },
    {
        id: 6,
        latitude: 39.5134274,
        longitude: -8.687879,
        title: "Festa 6",
        description: "desc1",
        image: "https://i.pinimg.com/originals/86/60/97/866097e05986c369e0db5f3658182f60.jpg",
        artista1: "Bob Marley",
        artista2: "Mike Davis",
        artista3: "Xutos e pontapes",
        dataInicio: '2020-06-11',
        dataFinal: '2020-06-12',
        codigo: "0006",
        art: [],
        allImages: [{
            photo: "https://source.unsplash.com/aZjw7xI3QAA/1144x763",
            caption: "Viñales, Pinar del Río, Cuba",
            subcaption: "Photo by Simon Matzinger on Unsplash",
            thumbnail: "https://source.unsplash.com/aZjw7xI3QAA/100x67",
        }, {
            photo: "https://source.unsplash.com/c77MgFOt7e0/1144x763",
            caption: "La Habana, Cuba",
            subcaption: "Photo by Gerardo Sanchez on Unsplash",
            thumbnail: "https://source.unsplash.com/c77MgFOt7e0/100x67",
        }, {
            photo: "https://source.unsplash.com/QdBHnkBdu4g/1144x763",
            caption: "Woman smoking a tobacco",
            subcaption: "Photo by Hannah Cauhepe on Unsplash",
            thumbnail: "https://source.unsplash.com/QdBHnkBdu4g/100x67",
        }]
    },
]